# permissions for end users to edit listeners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nebucloud-xds-operator
    app.kubernetes.io/managed-by: kustomize
  name: listener-editor-role
rules:
- apiGroups:
  - xds.xds.nebucloud.io
  resources:
  - listeners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xds.xds.nebucloud.io
  resources:
  - listeners/status
  verbs:
  - get
