apiVersion: xds.xds.nebucloud.io/v1alpha1
kind: Listener
metadata:
  labels:
    app.kubernetes.io/name: nebucloud-xds-operator
    app.kubernetes.io/managed-by: kustomize
  name: listener-sample
spec:
  # TODO(user): Add fields here
